// Who the simulated people are.
//
// A persona is a city, a platform, a rate, and behaviour weights that decide
// how often someone posts, chats, likes and takes breaks. The weights are the
// whole trick: a quiet courier who never posts sitting next to a rider who
// comments on everything is what makes a population read as people instead of
// a loop. Identical bots find identical bugs.
//
// This is the built-in "mobile workers" pack. Supply your own via
// `personas` in populace.config.mjs if your users are something else.

export const CITIES = {
  manila: { name: "Manila", lat: 14.5995, lng: 120.9842, country: "Philippines", currency: "PHP", rate: 10 },
  mumbai: { name: "Mumbai", lat: 19.076, lng: 72.8777, country: "India", currency: "INR", rate: 10 },
  delhi: { name: "Delhi", lat: 28.6139, lng: 77.209, country: "India", currency: "INR", rate: 10 },
  jakarta: { name: "Jakarta", lat: -6.2088, lng: 106.8456, country: "Indonesia", currency: "IDR", rate: 3000 },
  bangkok: { name: "Bangkok", lat: 13.7563, lng: 100.5018, country: "Thailand", currency: "THB", rate: 6 },
  // Rates are per-kilometre in the local currency, scaled the way the first
  // five are: roughly what a courier is paid, not an exchange-rate conversion.
  hcmc: { name: "Ho Chi Minh City", lat: 10.8231, lng: 106.6297, country: "Vietnam", currency: "VND", rate: 5000 },
  dhaka: { name: "Dhaka", lat: 23.8103, lng: 90.4125, country: "Bangladesh", currency: "BDT", rate: 22 },
  karachi: { name: "Karachi", lat: 24.8607, lng: 67.0011, country: "Pakistan", currency: "PKR", rate: 55 },
  kualalumpur: { name: "Kuala Lumpur", lat: 3.139, lng: 101.6869, country: "Malaysia", currency: "MYR", rate: 2 },
  bengaluru: { name: "Bengaluru", lat: 12.9716, lng: 77.5946, country: "India", currency: "INR", rate: 10 },
  lahore: { name: "Lahore", lat: 31.5204, lng: 74.3587, country: "Pakistan", currency: "PKR", rate: 55 },
  chennai: { name: "Chennai", lat: 13.0827, lng: 80.2707, country: "India", currency: "INR", rate: 10 },
  hyderabad: { name: "Hyderabad", lat: 17.385, lng: 78.4867, country: "India", currency: "INR", rate: 10 },
  kolkata: { name: "Kolkata", lat: 22.5726, lng: 88.3639, country: "India", currency: "INR", rate: 10 },
  hanoi: { name: "Hanoi", lat: 21.0278, lng: 105.8342, country: "Vietnam", currency: "VND", rate: 5000 },
  surabaya: { name: "Surabaya", lat: -7.2575, lng: 112.7521, country: "Indonesia", currency: "IDR", rate: 3000 },
  cebu: { name: "Cebu", lat: 10.3157, lng: 123.8854, country: "Philippines", currency: "PHP", rate: 10 },
  colombo: { name: "Colombo", lat: 6.9271, lng: 79.8612, country: "Sri Lanka", currency: "LKR", rate: 90 },
  kathmandu: { name: "Kathmandu", lat: 27.7172, lng: 85.324, country: "Nepal", currency: "NPR", rate: 35 },
  phnompenh: { name: "Phnom Penh", lat: 11.5564, lng: 104.9282, country: "Cambodia", currency: "KHR", rate: 800 },
  ahmedabad: { name: "Ahmedabad", lat: 23.0225, lng: 72.5714, country: "India", currency: "INR", rate: 10 },
  pune: { name: "Pune", lat: 18.5204, lng: 73.8567, country: "India", currency: "INR", rate: 10 },
  jaipur: { name: "Jaipur", lat: 26.9124, lng: 75.7873, country: "India", currency: "INR", rate: 10 },
  islamabad: { name: "Islamabad", lat: 33.6844, lng: 73.0479, country: "Pakistan", currency: "PKR", rate: 55 },
  chittagong: { name: "Chittagong", lat: 22.3569, lng: 91.7832, country: "Bangladesh", currency: "BDT", rate: 22 },
  danang: { name: "Da Nang", lat: 16.0544, lng: 108.2022, country: "Vietnam", currency: "VND", rate: 5000 },
  bandung: { name: "Bandung", lat: -6.9175, lng: 107.6191, country: "Indonesia", currency: "IDR", rate: 3000 },
  davao: { name: "Davao", lat: 7.1907, lng: 125.4553, country: "Philippines", currency: "PHP", rate: 10 },
  chiangmai: { name: "Chiang Mai", lat: 18.7883, lng: 98.9853, country: "Thailand", currency: "THB", rate: 6 },
  yangon: { name: "Yangon", lat: 16.8409, lng: 96.1735, country: "Myanmar", currency: "MMK", rate: 900 },

  // Beyond the original South and Southeast Asian market: one city per country,
  // taking the pack to forty countries. Rates stay per-kilometre in local money.
  saopaulo: { name: "São Paulo", lat: -23.5505, lng: -46.6333, country: "Brazil", currency: "BRL", rate: 5 },
  mexicocity: { name: "Mexico City", lat: 19.4326, lng: -99.1332, country: "Mexico", currency: "MXN", rate: 12 },
  bogota: { name: "Bogotá", lat: 4.711, lng: -74.0721, country: "Colombia", currency: "COP", rate: 2500 },
  buenosaires: { name: "Buenos Aires", lat: -34.6037, lng: -58.3816, country: "Argentina", currency: "ARS", rate: 800 },
  lima: { name: "Lima", lat: -12.0464, lng: -77.0428, country: "Peru", currency: "PEN", rate: 3 },
  santiago: { name: "Santiago", lat: -33.4489, lng: -70.6693, country: "Chile", currency: "CLP", rate: 600 },
  lagos: { name: "Lagos", lat: 6.5244, lng: 3.3792, country: "Nigeria", currency: "NGN", rate: 700 },
  nairobi: { name: "Nairobi", lat: -1.2921, lng: 36.8219, country: "Kenya", currency: "KES", rate: 60 },
  accra: { name: "Accra", lat: 5.6037, lng: -0.187, country: "Ghana", currency: "GHS", rate: 7 },
  cairo: { name: "Cairo", lat: 30.0444, lng: 31.2357, country: "Egypt", currency: "EGP", rate: 25 },
  johannesburg: { name: "Johannesburg", lat: -26.2041, lng: 28.0473, country: "South Africa", currency: "ZAR", rate: 10 },
  addisababa: { name: "Addis Ababa", lat: 9.032, lng: 38.7469, country: "Ethiopia", currency: "ETB", rate: 40 },
  daressalaam: { name: "Dar es Salaam", lat: -6.7924, lng: 39.2083, country: "Tanzania", currency: "TZS", rate: 1200 },
  kampala: { name: "Kampala", lat: 0.3476, lng: 32.5825, country: "Uganda", currency: "UGX", rate: 1800 },
  casablanca: { name: "Casablanca", lat: 33.5731, lng: -7.5898, country: "Morocco", currency: "MAD", rate: 5 },
  istanbul: { name: "Istanbul", lat: 41.0082, lng: 28.9784, country: "Turkey", currency: "TRY", rate: 15 },
  dubai: { name: "Dubai", lat: 25.2048, lng: 55.2708, country: "United Arab Emirates", currency: "AED", rate: 2 },
  riyadh: { name: "Riyadh", lat: 24.7136, lng: 46.6753, country: "Saudi Arabia", currency: "SAR", rate: 2 },
  baghdad: { name: "Baghdad", lat: 33.3152, lng: 44.3661, country: "Iraq", currency: "IQD", rate: 700 },
  amman: { name: "Amman", lat: 31.9454, lng: 35.9284, country: "Jordan", currency: "JOD", rate: 1 },
  moscow: { name: "Moscow", lat: 55.7558, lng: 37.6173, country: "Russia", currency: "RUB", rate: 40 },
  kyiv: { name: "Kyiv", lat: 50.4501, lng: 30.5234, country: "Ukraine", currency: "UAH", rate: 20 },
  warsaw: { name: "Warsaw", lat: 52.2297, lng: 21.0122, country: "Poland", currency: "PLN", rate: 3 },
  bucharest: { name: "Bucharest", lat: 44.4268, lng: 26.1025, country: "Romania", currency: "RON", rate: 3 },
  madrid: { name: "Madrid", lat: 40.4168, lng: -3.7038, country: "Spain", currency: "EUR", rate: 1 },
  almaty: { name: "Almaty", lat: 43.222, lng: 76.8512, country: "Kazakhstan", currency: "KZT", rate: 250 },
  tashkent: { name: "Tashkent", lat: 41.2995, lng: 69.2401, country: "Uzbekistan", currency: "UZS", rate: 6000 },
  baku: { name: "Baku", lat: 40.4093, lng: 49.8671, country: "Azerbaijan", currency: "AZN", rate: 1 },

  // Nine more, chosen for their scripts as much as their markets: Japanese,
  // Korean, Georgian and Serbian Cyrillic are new to the corpus.
  singapore: { name: "Singapore", lat: 1.3521, lng: 103.8198, country: "Singapore", currency: "SGD", rate: 1 },
  tokyo: { name: "Tokyo", lat: 35.6762, lng: 139.6503, country: "Japan", currency: "JPY", rate: 250 },
  seoul: { name: "Seoul", lat: 37.5665, lng: 126.978, country: "South Korea", currency: "KRW", rate: 1500 },
  tbilisi: { name: "Tbilisi", lat: 41.7151, lng: 44.8271, country: "Georgia", currency: "GEL", rate: 2 },
  belgrade: { name: "Belgrade", lat: 44.7866, lng: 20.4489, country: "Serbia", currency: "RSD", rate: 90 },
  lisbon: { name: "Lisbon", lat: 38.7223, lng: -9.1393, country: "Portugal", currency: "EUR", rate: 1 },
  milan: { name: "Milan", lat: 45.4642, lng: 9.19, country: "Italy", currency: "EUR", rate: 1 },
  dakar: { name: "Dakar", lat: 14.7167, lng: -17.4677, country: "Senegal", currency: "XOF", rate: 400 },
  quito: { name: "Quito", lat: -0.1807, lng: -78.4678, country: "Ecuador", currency: "USD", rate: 1 },
};

// Chatter is per-city so a feed reads like the right place.
const CHATTER = {
  manila: [
    "Heavy traffic sa EDSA southbound, mag-alternate route kayo",
    "Surge ngayon sa BGC, sulit ang pila",
    "Ingat sa Commonwealth, may flood sa gilid",
    "Sino nandito sa Ortigas? Ang dami booking",
    "Break muna, 6 hours na akong byahe",
  ],
  mumbai: [
    "Andheri me bahut traffic hai, Link Road se jao",
    "Bandra side surge chal raha hai abhi",
    "Sion flyover pe jam, 25 min lag rahe hain",
    "Koi Powai me hai? Bookings kaafi aa rahe hain",
    "Chai break, subah se 80 km ho gaye",
  ],
  delhi: [
    "Ring Road pe heavy jam, Outer se nikal jao",
    "Connaught Place me surge hai abhi",
    "Gurgaon toll pe lambi line lagi hai",
    "Metro strike ki wajah se bookings badh gaye",
    "Paani pi lo bhai, aaj bahut garmi hai",
  ],
  jakarta: [
    "Macet parah di Sudirman, lewat jalan tikus aja",
    "Lagi surge di Kuningan, lumayan",
    "Hati-hati banjir di Kemang",
    "Ada yang di Senayan? Orderan rame",
    "Istirahat dulu, udah 7 jam narik",
  ],
  bangkok: [
    "รถติดมากแถวสุขุมวิท ใช้ทางด่วนดีกว่า",
    "ตอนนี้ราคาขึ้นแถวสีลม",
    "ระวังน้ำท่วมแถวลาดพร้าว",
    "ใครอยู่แถวอโศกบ้าง งานเยอะมาก",
    "พักก่อน วิ่งมา 6 ชั่วโมงแล้ว",
  ],
  hcmc: [
    "Kẹt xe dữ lắm ở Điện Biên Phủ, đi đường khác đi",
    "Đang có thưởng khu Quận 1, chạy đi anh em",
    "Cẩn thận ngập nước ở Thảo Điền nha",
    "Ai đang ở Phú Nhuận không? Đơn nhiều lắm",
    "Nghỉ chút đã, chạy 7 tiếng rồi",
  ],
  dhaka: [
    "গুলশানে অনেক জ্যাম, বিকল্প রাস্তা নিন",
    "মতিঝিলে এখন সার্জ চলছে",
    "ধানমন্ডিতে পানি জমেছে, সাবধানে",
    "বনানীতে কেউ আছেন? অনেক অর্ডার আসছে",
    "একটু বিশ্রাম নিচ্ছি, ৮ ঘণ্টা হয়ে গেল",
  ],
  karachi: [
    "شاہراہِ فیصل پر بہت رش ہے، دوسرا راستہ لیں",
    "کلفٹن میں ابھی سرج چل رہا ہے",
    "ڈیفنس میں پانی کھڑا ہے، احتیاط کریں",
    "کوئی گلشن اقبال میں ہے؟ آرڈر بہت آ رہے ہیں",
    "تھوڑا آرام کر لوں، سات گھنٹے ہو گئے",
  ],
  kualalumpur: [
    "Jam teruk kat Jalan Tun Razak, ambil jalan lain",
    "Ada surge kat KLCC sekarang",
    "Hati-hati banjir kilat kat Bangsar",
    "Sesiapa kat Cheras? Banyak order masuk",
    "Rehat kejap, dah 7 jam bawa motor",
  ],
  bengaluru: [
    "Silk Board nalli traffic jaasti ide, bere route togolli",
    "Koramangala kade surge idhe eega",
    "Outer Ring Road nalli neeru nintide, hushar",
    "Yaaru Whitefield nalli iddira? Orders tumba bartaide",
    "Swalpa rest, belagininda 90 km aagide",
  ],
  lahore: [
    "فیروزپور روڈ پر بہت ٹریفک ہے، دوسرا راستہ لیں",
    "گلبرگ میں ابھی سرج لگا ہوا ہے",
    "ڈی ایچ اے میں پانی کھڑا ہے، دھیان سے",
    "کوئی جوہر ٹاؤن میں ہے؟ آرڈر بہت ہیں",
    "چائے کا وقفہ، صبح سے ستر کلومیٹر ہو گئے",
  ],
  chennai: [
    "Anna Salai la romba traffic, vera route la ponga",
    "T Nagar pakkam ippo surge irukku",
    "Velachery la thanni thengi irukku, jaakirathai",
    "Yaaru OMR la irukkeenga? Orders niraya varuthu",
    "Konjam rest, kaalaila irunthu 80 km aachu",
  ],
  hyderabad: [
    "Hitech City daggara traffic ekkuva undi, vere route veldam",
    "Banjara Hills lo ippudu surge nadustondi",
    "Kukatpally lo neellu nilichayi, jagratha",
    "Evaraina Gachibowli lo unnara? Orders baaga vastunnayi",
    "Konchem rest, udayam nunchi 85 km ayindi",
  ],
  kolkata: [
    "ই এম বাইপাসে প্রচুর জ্যাম, অন্য রাস্তা ধরুন",
    "পার্ক স্ট্রিটে এখন সার্জ চলছে",
    "সল্টলেকে জল জমেছে, সাবধানে চালান",
    "কেউ কি হাওড়ায় আছেন? অর্ডার প্রচুর আসছে",
    "একটু চা খেয়ে নিই, সকাল থেকে ৭৫ কিলোমিটার",
  ],
  hanoi: [
    "Tắc đường kinh khủng ở Trường Chinh, đi lối khác nhé",
    "Đang có thưởng khu Hoàn Kiếm, tranh thủ đi",
    "Cẩn thận ngập ở Thái Hà nhé anh em",
    "Ai đang ở Cầu Giấy không? Đơn về nhiều lắm",
    "Nghỉ tí đã, chạy từ sáng được 80 cây rồi",
  ],
  surabaya: [
    "Macet parah di Ahmad Yani, lewat jalan lain aja",
    "Lagi surge di Tunjungan, lumayan nih",
    "Hati-hati genangan di Rungkut",
    "Ada yang di Gubeng? Orderan rame banget",
    "Istirahat dulu, udah 8 jam narik",
  ],
  cebu: [
    "Grabe ang traffic sa Colon, lain dalan na lang",
    "Naay surge karon sa IT Park, sulit",
    "Bantay sa baha sa Mandaue, hinay-hinay",
    "Kinsa naa sa Lahug? Daghan kaayo booking",
    "Pahulay sa, 7 oras na ko nagdrive",
  ],
  colombo: [
    "ගාලු පාරේ විශාල රථවාහන තදබදයක්, වෙන පාරකින් යන්න",
    "දැන් කොල්ලුපිටියේ සර්ජ් එකක් තියෙනවා",
    "දෙහිවලේ වතුර පිරිලා, පරිස්සමෙන්",
    "නුගේගොඩ ඉන්නේ කවුද? ඕඩර් ගොඩක් එනවා",
    "පොඩි විවේකයක්, උදේ ඉඳන් කිලෝමීටර් 70යි",
  ],
  kathmandu: [
    "कोटेश्वरमा धेरै जाम छ, अर्को बाटो जानुहोस्",
    "अहिले ठमेलमा सर्ज चलिरहेको छ",
    "बल्खुमा पानी जमेको छ, ध्यान दिनुहोस्",
    "कोही ललितपुरमा हुनुहुन्छ? अर्डर धेरै आइरहेको छ",
    "अलिकति आराम, बिहानदेखि ६० किलोमिटर भयो",
  ],
  phnompenh: [
    "ស្ទះចរាចរណ៍ខ្លាំងនៅមហាវិថីមុនីវង្ស សូមប្រើផ្លូវផ្សេង",
    "ឥឡូវមានតម្លៃឡើងនៅបឹងកេងកង",
    "ប្រយ័ត្នទឹកជន់នៅទួលគោក",
    "អ្នកណានៅចំការមនទេ? ការកម្ម៉ង់ច្រើនណាស់",
    "សម្រាកបន្តិច បើកបានប្រាំពីរម៉ោងហើយ",
  ],
  ahmedabad: [
    "એસ જી હાઈવે પર બહુ ટ્રાફિક છે, બીજો રસ્તો લો",
    "અત્યારે સી જી રોડ પર સર્જ ચાલે છે",
    "મણિનગરમાં પાણી ભરાયું છે, સાચવીને",
    "કોઈ વસ્ત્રાપુરમાં છે? ઓર્ડર બહુ આવે છે",
    "થોડો આરામ, સવારથી ૭૫ કિલોમીટર થયા",
  ],
  pune: [
    "हिंजवडीला खूप ट्रॅफिक आहे, दुसऱ्या रस्त्याने जा",
    "कोरेगाव पार्कला आत्ता सर्ज चालू आहे",
    "कात्रजला पाणी साचलंय, जपून चला",
    "कोणी विमाननगरला आहे का? ऑर्डर खूप येतायत",
    "जरा आराम, सकाळपासून ८० किलोमीटर झाले",
  ],
  jaipur: [
    "टोंक रोड पर बहुत जाम है, दूसरा रास्ता लो",
    "एम आई रोड पर अभी सर्ज चल रहा है",
    "मानसरोवर में पानी भर गया, संभल के",
    "कोई वैशाली नगर में है? ऑर्डर बहुत आ रहे",
    "थोड़ा आराम, सुबह से ७० किलोमीटर हो गए",
  ],
  islamabad: [
    "سری نگر ہائی وے پر رش ہے، دوسرا راستہ لیں",
    "بلیو ایریا میں ابھی سرج ہے",
    "جی الیون میں پانی کھڑا ہے، احتیاط",
    "کوئی ایف سیون میں ہے؟ آرڈر بہت ہیں",
    "تھوڑا آرام، صبح سے پینسٹھ کلومیٹر",
  ],
  chittagong: [
    "আগ্রাবাদে অনেক জ্যাম, অন্য রাস্তা ধরুন",
    "জিইসি মোড়ে এখন সার্জ চলছে",
    "চকবাজারে পানি জমেছে, সাবধানে",
    "কেউ কি খুলশীতে আছেন? অর্ডার অনেক",
    "একটু বিশ্রাম, সকাল থেকে ৭০ কিলোমিটার",
  ],
  danang: [
    "Kẹt xe ở cầu Rồng, đi đường khác nhé",
    "Đang có thưởng khu Hải Châu",
    "Cẩn thận ngập ở Thanh Khê nha",
    "Ai đang ở Sơn Trà không? Đơn nhiều lắm",
    "Nghỉ chút, chạy từ sáng được 65 cây",
  ],
  bandung: [
    "Macet di Pasteur, lewat jalan lain aja",
    "Lagi surge di Dago, lumayan",
    "Hati-hati genangan di Kiaracondong",
    "Ada yang di Buah Batu? Orderan rame",
    "Istirahat dulu, udah 7 jam narik",
  ],
  davao: [
    "Grabe ang traffic sa Quimpo, lain dalan na lang",
    "Naay surge karon sa Lanang",
    "Bantay sa baha sa Matina, hinay lang",
    "Kinsa naa sa Buhangin? Daghan booking",
    "Pahulay sa, 7 oras na ko nagdrive",
  ],
  chiangmai: [
    "รถติดแถวช้างเผือก ใช้ทางอื่นดีกว่า",
    "ตอนนี้ราคาขึ้นแถวนิมมาน",
    "ระวังน้ำท่วมแถวสันทราย",
    "ใครอยู่แถวสันกำแพงบ้าง งานเยอะ",
    "พักก่อน วิ่งมา 6 ชั่วโมงแล้ว",
  ],
  yangon: [
    "ပြည်လမ်းမှာ ကားပိတ်နေတယ်၊ တခြားလမ်းသွားပါ",
    "အခု ဗိုလ်ချုပ်လမ်းမှာ ဈေးတက်နေတယ်",
    "လှိုင်မှာ ရေဝပ်နေတယ်၊ သတိထားပါ",
    "ကမာရွတ်မှာ ဘယ်သူရှိလဲ။ အော်ဒါတွေများတယ်",
    "ခဏနားလိုက်ဦးမယ်၊ မနက်ကတည်းက ၆၀ ကီလို",
  ],
  saopaulo: [
    "Trânsito parado na Marginal, pega outro caminho",
    "Tá com dinâmica alta na Paulista agora",
    "Cuidado com o alagamento na Radial Leste",
    "Alguém na Vila Olímpia? Tá chovendo pedido",
    "Vou parar pra um café, 80 km desde cedo",
  ],
  mexicocity: [
    "Tráfico pesado en Periférico, agarren otra ruta",
    "Hay tarifa dinámica en Polanco ahorita",
    "Aguas con el encharcamiento en Viaducto",
    "¿Alguien por Condesa? Están cayendo muchos pedidos",
    "Me paro tantito, llevo 7 horas rodando",
  ],
  bogota: [
    "Trancón bravo en la Boyacá, cojan otra vía",
    "Está en dinámica la zona T ahora",
    "Ojo con el encharcamiento en la 68",
    "¿Alguien por Chapinero? Entran hartos domicilios",
    "Paro un rato, llevo 75 km desde la mañana",
  ],
  buenosaires: [
    "Está imposible el tránsito en General Paz, tomen otra",
    "Hay tarifa alta en Palermo ahora",
    "Ojo que se inunda en Constitución",
    "¿Alguien por Belgrano? Entran un montón de pedidos",
    "Corto un rato, ya hice 80 km",
  ],
  lima: [
    "Tráfico pesado en la Javier Prado, agarren otra ruta",
    "Está con tarifa alta Miraflores ahorita",
    "Cuidado con el hueco en la Panamericana",
    "¿Alguien por San Isidro? Caen hartos pedidos",
    "Paro un rato, 7 horas manejando",
  ],
  santiago: [
    "Taco terrible en la Kennedy, tomen otra ruta",
    "Está con tarifa alta Providencia ahora",
    "Ojo con la anegación en Vicuña Mackenna",
    "¿Alguien por Ñuñoa? Están cayendo hartos pedidos",
    "Paro un rato, llevo 70 km",
  ],
  lagos: [
    "Traffic don hold for Third Mainland, use another road",
    "Surge dey for Lekki now o",
    "Water don gather for Ojota, waka softly",
    "Anybody dey Ikeja? Orders plenty well well",
    "Make I rest small, I don do 6 hours",
  ],
  nairobi: [
    "Traffic imesimama Mombasa Road, tumia njia nyingine",
    "Kuna surge Westlands sasa hivi",
    "Angalia maji yamejaa Ngong Road",
    "Kuna mtu Kilimani? Orders ni nyingi sana",
    "Nipumzike kidogo, nimefanya masaa saba",
  ],
  accra: [
    "Traffic is heavy on Spintex, take another route",
    "There's surge in Osu right now",
    "Careful, water has gathered at Kwame Nkrumah Circle",
    "Anyone around East Legon? Orders are plenty",
    "Let me rest small, I've done 6 hours",
  ],
  cairo: [
    "زحمة شديدة في صلاح سالم، خدوا طريق تاني",
    "في تسعيرة عالية في المهندسين دلوقتي",
    "خلي بالك من المياه في شبرا",
    "حد في مدينة نصر؟ الطلبات كتير",
    "هريح شوية، بقالي سبع ساعات",
  ],
  johannesburg: [
    "Traffic is bad on the M1, take another route",
    "There's surge in Sandton right now",
    "Watch out for flooding in Braamfontein",
    "Anyone in Rosebank? Orders are coming in fast",
    "Let me take a break, seven hours already",
  ],
  addisababa: [
    "ቦሌ አካባቢ መንገዱ ተጨናንቋል፣ ሌላ መንገድ ይያዙ",
    "አሁን መርካቶ አካባቢ ዋጋ ጨምሯል",
    "ካዛንቺስ ውሃ ቆሟል፣ ተጠንቀቁ",
    "ፒያሳ ያለ አለ? ትዕዛዝ በጣም ብዙ ነው",
    "ትንሽ ላረፍ፣ ሰባት ሰዓት ሆኖኛል",
  ],
  daressalaam: [
    "Msongamano mkubwa Morogoro Road, tumia njia nyingine",
    "Kuna bei juu Masaki sasa hivi",
    "Angalia maji Kariakoo, endesha polepole",
    "Kuna mtu Mikocheni? Oda ni nyingi",
    "Nipumzike kidogo, masaa saba tayari",
  ],
  kampala: [
    "Traffic is heavy on Entebbe Road, use another route",
    "There's surge in Kololo right now",
    "Careful with the water at Clock Tower",
    "Anyone in Ntinda? Orders are plenty",
    "Let me rest a bit, seven hours already",
  ],
  casablanca: [
    "السير خانق فبولفار زرقطوني، دوزو من طريق أخرى",
    "كاين تسعيرة عالية فعين الذياب دابا",
    "عندكم الما تجمع فسيدي البرنوصي",
    "شي واحد فالمعاريف؟ الطلبات بزاف",
    "غادي نرتاح شوية، دزت سبع سوايع",
  ],
  istanbul: [
    "E-5'te trafik çok yoğun, başka yoldan gidin",
    "Şu an Kadıköy'de fiyat yüksek",
    "Mecidiyeköy'de su birikmiş, dikkat edin",
    "Beşiktaş'ta olan var mı? Sipariş çok geliyor",
    "Biraz mola vereyim, yedi saat oldu",
  ],
  dubai: [
    "ازدحام شديد على شارع الشيخ زايد، خذوا طريق آخر",
    "في تسعيرة مرتفعة في المارينا الآن",
    "انتبهوا للمياه في ديرة",
    "حد في الخليج التجاري؟ الطلبات كثيرة",
    "بأخذ استراحة، صار لي سبع ساعات",
  ],
  riyadh: [
    "زحمة على طريق الملك فهد، خذوا طريق ثاني",
    "فيه تسعيرة مرتفعة في العليا الحين",
    "انتبهوا للمياه في السويدي",
    "أحد في الملز؟ الطلبات كثيرة",
    "بارتاح شوي، صار لي سبع ساعات",
  ],
  baghdad: [
    "زحمة قوية بشارع فلسطين، خذوا طريق ثاني",
    "أكو تسعيرة عالية بالكرادة هسه",
    "انتبهوا للماي بالدورة",
    "أكو أحد بالمنصور؟ الطلبات هواي",
    "راح أرتاح شوية، صارلي سبع ساعات",
  ],
  amman: [
    "زحمة كتير عالمدينة الرياضية، خذوا طريق تاني",
    "في تسعيرة عالية بعبدون هلق",
    "انتبهوا للمي بوسط البلد",
    "في حدا بالصويفية؟ الطلبات كتير",
    "بدي أرتاح شوي، صارلي سبع ساعات",
  ],
  moscow: [
    "Пробка на ТТК, поезжайте другой дорогой",
    "Сейчас повышенный тариф в Москва-Сити",
    "Осторожно, вода на Ленинградке",
    "Кто-нибудь на Тверской? Заказов очень много",
    "Передохну немного, семь часов за рулём",
  ],
  kyiv: [
    "Затор на Броварському, їдьте іншою дорогою",
    "Зараз підвищений тариф на Печерську",
    "Обережно, вода на Оболоні",
    "Хтось на Позняках? Замовлень дуже багато",
    "Трохи відпочину, сім годин за кермом",
  ],
  warsaw: [
    "Korek na Wisłostradzie, jedźcie inną trasą",
    "Teraz jest wyższa stawka na Mokotowie",
    "Uwaga, woda na Marszałkowskiej",
    "Ktoś na Woli? Zamówień jest dużo",
    "Zrobię sobie przerwę, siedem godzin już",
  ],
  bucharest: [
    "Trafic infernal pe Centura, luați altă rută",
    "Acum e tarif mărit în Pipera",
    "Atenție la apa de pe Berceni",
    "E cineva prin Dorobanți? Vin multe comenzi",
    "Iau o pauză, sunt de șapte ore pe drum",
  ],
  madrid: [
    "Atasco tremendo en la M-30, coged otra ruta",
    "Ahora hay tarifa alta en Chamberí",
    "Cuidado con el agua en Atocha",
    "¿Alguien por Malasaña? Están entrando muchos pedidos",
    "Voy a descansar un rato, llevo siete horas",
  ],
  almaty: [
    "Пробка на Аль-Фараби, езжайте другой дорогой",
    "Сейчас повышенный тариф в центре",
    "Осторожно, вода на Райымбека",
    "Кто-нибудь на Достык? Заказов очень много",
    "Отдохну немного, семь часов уже",
  ],
  tashkent: [
    "Chilonzorda tirbandlik katta, boshqa yo'ldan boring",
    "Hozir markazda narx oshgan",
    "Yunusobodda suv yig'ilgan, ehtiyot bo'ling",
    "Sergelida kim bor? Buyurtma juda ko'p",
    "Biroz dam olay, yetti soat bo'ldi",
  ],
  baku: [
    "Tıxac var Heydər Əliyev prospektində, başqa yolla gedin",
    "İndi Nərimanovda qiymət yüksəkdir",
    "Diqqətli olun, Xətaidə su yığılıb",
    "Yasamalda kim var? Sifariş çox gəlir",
    "Bir az dincələcəm, yeddi saatdır sürürəm",
  ],
  singapore: [
    "Jam quite bad along PIE, take CTE instead",
    "Surge at Orchard now, worth queueing",
    "Careful, flash flood at Bukit Timah",
    "Anyone at Tampines? Orders coming in fast",
    "Taking a break lah, 7 hours already",
  ],
  tokyo: [
    "環七が渋滞してます、別ルートで",
    "今、渋谷エリアは料金アップ中です",
    "品川あたり冠水注意してください",
    "新宿にいる人いますか？注文が多いです",
    "少し休憩します、7時間走りました",
  ],
  seoul: [
    "강변북로 정체 심해요, 다른 길로 가세요",
    "지금 강남 할증 붙었습니다",
    "여의도 물 고였어요, 조심하세요",
    "홍대 근처 계신 분? 콜 엄청 많아요",
    "잠깐 쉬겠습니다, 7시간 됐네요",
  ],
  tbilisi: [
    "დიდი საცობია რუსთაველზე, სხვა გზით წადით",
    "ახლა ვაკეში ფასი აწეულია",
    "საბურთალოზე წყალი დგას, ფრთხილად",
    "ვინმე ვარკეთილში ხართ? შეკვეთები ბევრია",
    "ცოტა დავისვენებ, შვიდი საათია",
  ],
  belgrade: [
    "Велика гужва на Аутокоманди, идите другим путем",
    "Сада је виша цена на Врачару",
    "Пажљиво, вода на Новом Београду",
    "Има ли неко на Дорћолу? Много поруџбина",
    "Одмарам мало, седам сати већ",
  ],
  lisbon: [
    "Trânsito parado na Segunda Circular, vão por outro lado",
    "Está com tarifa alta no Chiado agora",
    "Cuidado com a água em Alcântara",
    "Alguém em Benfica? Estão a entrar muitos pedidos",
    "Vou parar um bocado, sete horas já",
  ],
  milan: [
    "Traffico bloccato sulla Tangenziale, prendete un'altra strada",
    "Adesso c'è tariffa alta in Porta Nuova",
    "Attenzione all'acqua in Navigli",
    "C'è qualcuno a Lambrate? Arrivano tanti ordini",
    "Faccio una pausa, sono sette ore",
  ],
  dakar: [
    "Gros embouteillage sur la VDN, prenez une autre route",
    "Il y a une majoration aux Almadies maintenant",
    "Attention à l'eau à Pikine",
    "Quelqu'un à Ouakam ? Les commandes arrivent beaucoup",
    "Je fais une pause, ça fait sept heures",
  ],
  quito: [
    "Tráfico pesado en la Simón Bolívar, cojan otra ruta",
    "Está con tarifa alta La Carolina ahorita",
    "Ojo con el agua en el Centro Histórico",
    "¿Alguien por Cumbayá? Están entrando hartos pedidos",
    "Paro un rato, llevo siete horas",
  ],
};

const REPLIES = [
  "Thanks for the heads up 🙏",
  "Same here, confirmed",
  "Good to know, avoiding that route",
  "How long is the wait?",
  "Salamat / Thanks bhai",
  "On my way there now",
];

const NAMES = {
  manila: ["Jhun Ramirez", "Maricel Santos", "Dante Cruz", "Liza Bautista", "Noel Aquino"],
  mumbai: ["Ramesh Kadam", "Priya Sharma", "Imran Shaikh", "Sunita Patil", "Arjun Nair"],
  delhi: ["Vikas Yadav", "Neha Gupta", "Rahul Verma", "Pooja Singh", "Manoj Kumar"],
  jakarta: ["Budi Santoso", "Siti Rahayu", "Agus Wijaya", "Dewi Lestari", "Eko Prasetyo"],
  bangkok: ["Somchai Prasert", "Ratana Wong", "Niran Suk", "Malee Chai", "Kittipong S."],
  hcmc: ["Nguyen Van Hung", "Tran Thi Mai", "Le Minh Tuan", "Pham Thu Ha", "Vo Quoc Bao"],
  dhaka: ["Rafiqul Islam", "Nasrin Akter", "Shahin Alam", "Taslima Begum", "Jamal Uddin"],
  karachi: ["Asif Mehmood", "Ayesha Khan", "Bilal Ahmed", "Farah Siddiqui", "Usman Raza"],
  kualalumpur: ["Ahmad Faizal", "Nurul Aina", "Tan Wei Ming", "Siti Zubaidah", "Ravi Kumar"],
  bengaluru: ["Manjunath Rao", "Deepa Shetty", "Kiran Gowda", "Lakshmi Prasad", "Suresh Babu"],
  lahore: ["Tariq Javed", "Sadia Malik", "Imran Butt", "Rabia Nawaz", "Zeeshan Iqbal"],
  chennai: ["Murugan Selvam", "Kavitha Raman", "Arun Prakash", "Divya Krishnan", "Senthil Kumar"],
  hyderabad: ["Venkatesh Reddy", "Swathi Rao", "Naveen Chandra", "Padma Latha", "Srinivas Goud"],
  kolkata: ["Subhas Ghosh", "Ananya Das", "Bikash Mondal", "Rituparna Sen", "Debasish Roy"],
  hanoi: ["Do Van Long", "Bui Thi Lan", "Hoang Minh Duc", "Ngo Thu Trang", "Dang Quoc Anh"],
  surabaya: ["Slamet Wibowo", "Rina Kusuma", "Bambang Setiawan", "Endah Puspita", "Joko Susilo"],
  cebu: ["Junjun Abella", "Rosalie Yap", "Boyet Villar", "Marites Go", "Dodong Lim"],
  colombo: ["Nuwan Perera", "Chamari Silva", "Kasun Fernando", "Dilani Jayasuriya", "Sampath Ranasinghe"],
  kathmandu: ["Bikash Thapa", "Sunita Shrestha", "Ramesh Adhikari", "Anjali Gurung", "Prakash Tamang"],
  phnompenh: ["Sokha Chan", "Sreymom Kim", "Vuthy Sok", "Bopha Meas", "Dara Heng"],
  ahmedabad: ["Jignesh Patel", "Hetal Shah", "Kalpesh Desai", "Bhavna Mehta", "Nilesh Trivedi"],
  pune: ["Sachin Deshmukh", "Snehal Joshi", "Amol Kulkarni", "Manasi Pawar", "Nitin Jadhav"],
  jaipur: ["Mahendra Meena", "Sunita Choudhary", "Dinesh Saini", "Rekha Sharma", "Vijay Rathore"],
  islamabad: ["Kamran Abbasi", "Hina Shah", "Waqar Khattak", "Sana Gul", "Adnan Qureshi"],
  chittagong: ["Mizanur Rahman", "Shirin Sultana", "Anwar Hossain", "Rumana Khatun", "Faisal Chowdhury"],
  danang: ["Truong Van Nam", "Le Thi Hoa", "Phan Minh Khoa", "Nguyen Thuy Linh", "Huynh Tan Phat"],
  bandung: ["Asep Suryadi", "Nining Herlina", "Dadang Hermawan", "Euis Rohaeti", "Yusuf Maulana"],
  davao: ["Nonoy Bautista", "Cherry Lou Diaz", "Toto Mendoza", "Baby Jane Ong", "Jomar Alcantara"],
  chiangmai: ["Anucha Pongsri", "Wilai Boonmee", "Somsak Inta", "Praewa Chaiyo", "Thanet Kaewta"],
  yangon: ["Aung Ko Min", "Thida Win", "Zaw Lin Htet", "Nilar Aye", "Kyaw Soe Moe"],
  saopaulo: ["Carlos Silva", "Ana Oliveira", "Rafael Souza", "Juliana Costa", "Bruno Santos"],
  mexicocity: ["Juan Hernández", "María López", "Luis García", "Guadalupe Ramírez", "Jorge Martínez"],
  bogota: ["Andrés Rodríguez", "Catalina Gómez", "Julián Moreno", "Paola Vargas", "Camilo Ruiz"],
  buenosaires: ["Matías Fernández", "Sofía Romero", "Nicolás Álvarez", "Lucía Benítez", "Diego Sosa"],
  lima: ["José Quispe", "Rosa Huamán", "Carlos Mamani", "Elena Flores", "Miguel Castillo"],
  santiago: ["Sebastián Muñoz", "Camila Rojas", "Felipe Contreras", "Valentina Soto", "Rodrigo Díaz"],
  lagos: ["Chinedu Okafor", "Aisha Bello", "Tunde Adeyemi", "Ngozi Eze", "Musa Ibrahim"],
  nairobi: ["Peter Kamau", "Grace Wanjiru", "Brian Otieno", "Mercy Achieng", "Samuel Mwangi"],
  accra: ["Kwame Mensah", "Akosua Boateng", "Yaw Owusu", "Abena Asante", "Kofi Darko"],
  cairo: ["Ahmed Hassan", "Fatma Ali", "Mohamed Saad", "Nour Ibrahim", "Mostafa Zaki"],
  johannesburg: ["Sipho Nkosi", "Thandi Dlamini", "Bongani Mokoena", "Lerato Molefe", "Jabu Sithole"],
  addisababa: ["Abebe Tadesse", "Selam Girma", "Dawit Bekele", "Hanan Ahmed", "Yonas Haile"],
  daressalaam: ["Juma Mwakyusa", "Neema Kimaro", "Hamisi Said", "Zawadi Mushi", "Baraka Massawe"],
  kampala: ["Moses Okello", "Sarah Nakato", "David Ssempa", "Grace Namuli", "Joseph Mugisha"],
  casablanca: ["Youssef El Amrani", "Fatima Zahra", "Karim Benali", "Salma Idrissi", "Rachid Ouali"],
  istanbul: ["Mehmet Yılmaz", "Ayşe Demir", "Mustafa Kaya", "Zeynep Şahin", "Emre Çelik"],
  dubai: ["Rashid Al Maktoum", "Layla Hassan", "Omar Farooq", "Mariam Saeed", "Bilal Ahmed"],
  riyadh: ["Abdullah Al Qahtani", "Noura Al Saud", "Fahad Al Otaibi", "Reem Al Harbi", "Saud Al Dosari"],
  baghdad: ["Ali Al Jubouri", "Zainab Hussein", "Omar Al Ani", "Hala Kadhim", "Mustafa Salim"],
  amman: ["Khaled Al Masri", "Rania Haddad", "Samer Odeh", "Dina Qasem", "Tareq Nasser"],
  moscow: ["Ivan Petrov", "Olga Smirnova", "Dmitry Kuznetsov", "Elena Popova", "Sergey Volkov"],
  kyiv: ["Oleksandr Kovalenko", "Iryna Bondarenko", "Andriy Tkachenko", "Nataliya Shevchenko", "Vitaliy Melnyk"],
  warsaw: ["Piotr Nowak", "Anna Kowalska", "Marek Wójcik", "Katarzyna Lewandowska", "Tomasz Zieliński"],
  bucharest: ["Andrei Popescu", "Elena Ionescu", "Mihai Radu", "Ioana Dumitru", "Cristian Stan"],
  madrid: ["Javier García", "Lucía Fernández", "Sergio Martín", "Carmen Ruiz", "Álvaro Jiménez"],
  almaty: ["Nurlan Abenov", "Aigul Serikova", "Yerlan Kassymov", "Dana Nurpeisova", "Timur Zhaksybek"],
  tashkent: ["Aziz Karimov", "Nilufar Rashidova", "Bekzod Tursunov", "Malika Yusupova", "Sardor Ergashev"],
  baku: ["Elvin Mammadov", "Leyla Aliyeva", "Rashad Huseynov", "Nigar Guliyeva", "Orkhan Ismayilov"],
  singapore: ["Tan Wei Jie", "Siti Nurhaliza", "Ravi Subramaniam", "Lim Mei Ling", "Muhammad Faizal"],
  tokyo: ["Hiroshi Tanaka", "Yuki Sato", "Kenji Suzuki", "Aiko Watanabe", "Takeshi Yamamoto"],
  seoul: ["Kim Min-jun", "Lee Ji-woo", "Park Seo-yun", "Choi Dong-hyun", "Jung Ha-eun"],
  tbilisi: ["Giorgi Beridze", "Nino Kapanadze", "Levan Gogoladze", "Tamar Chkheidze", "Davit Maisuradze"],
  belgrade: ["Marko Petrović", "Jelena Nikolić", "Stefan Jovanović", "Ana Đorđević", "Nikola Ilić"],
  lisbon: ["João Silva", "Maria Santos", "Pedro Ferreira", "Ana Costa", "Tiago Oliveira"],
  milan: ["Marco Rossi", "Giulia Bianchi", "Luca Ferrari", "Sofia Romano", "Alessandro Conti"],
  dakar: ["Moussa Diop", "Aminata Ndiaye", "Cheikh Fall", "Fatou Sarr", "Ibrahima Sow"],
  quito: ["Carlos Andrade", "María Guerrero", "Luis Paredes", "Gabriela Vaca", "Diego Chávez"],
};

const PLATFORMS = {
  manila: ["grab", "angkas", "joyride", "foodpanda", "lalamove"],
  mumbai: ["uber", "ola", "swiggy", "zomato", "rapido"],
  delhi: ["uber", "ola", "blinkit", "zepto", "amazon"],
  jakarta: ["gojek", "grab", "shopeefood", "maxim", "indrive"],
  bangkok: ["grab", "foodpanda", "lalamove", "shopeefood", "bolt"],
  hcmc: ["grab", "be", "gojek", "shopeefood", "ahamove"],
  dhaka: ["pathao", "uber", "foodpanda", "shohoz", "chaldal"],
  karachi: ["careem", "bykea", "indrive", "foodpanda", "yango"],
  kualalumpur: ["grab", "foodpanda", "lalamove", "shopeefood", "maxim"],
  bengaluru: ["uber", "ola", "swiggy", "zomato", "rapido"],
  lahore: ["careem", "bykea", "indrive", "foodpanda", "yango"],
  chennai: ["uber", "ola", "swiggy", "zomato", "rapido"],
  hyderabad: ["uber", "ola", "swiggy", "zomato", "rapido"],
  kolkata: ["uber", "ola", "swiggy", "zomato", "rapido"],
  hanoi: ["grab", "be", "gojek", "shopeefood", "ahamove"],
  surabaya: ["gojek", "grab", "shopeefood", "maxim", "indrive"],
  cebu: ["grab", "angkas", "joyride", "foodpanda", "lalamove"],
  colombo: ["pickme", "uber", "ubereats", "kangaroo", "darazfood"],
  kathmandu: ["pathao", "indrive", "foodmandu", "tootle", "bhojdeals"],
  phnompenh: ["grab", "passapp", "nham24", "foodpanda", "wownow"],
  ahmedabad: ["uber", "ola", "swiggy", "zomato", "rapido"],
  pune: ["uber", "ola", "swiggy", "zomato", "rapido"],
  jaipur: ["uber", "ola", "swiggy", "zomato", "rapido"],
  islamabad: ["careem", "bykea", "indrive", "foodpanda", "yango"],
  chittagong: ["pathao", "uber", "foodpanda", "shohoz", "chaldal"],
  danang: ["grab", "be", "gojek", "shopeefood", "ahamove"],
  bandung: ["gojek", "grab", "shopeefood", "maxim", "indrive"],
  davao: ["grab", "angkas", "joyride", "foodpanda", "lalamove"],
  chiangmai: ["grab", "foodpanda", "lalamove", "shopeefood", "bolt"],
  yangon: ["grab", "oway", "foodpanda", "yangonD2D", "hlaw"],
  saopaulo: ["99", "ifood", "uber", "rappi", "loggi"],
  mexicocity: ["uber", "didi", "rappi", "beat", "cornershop"],
  bogota: ["rappi", "uber", "didi", "picap", "cabify"],
  buenosaires: ["rappi", "pedidosya", "uber", "cabify", "didi"],
  lima: ["rappi", "pedidosya", "uber", "didi", "cabify"],
  santiago: ["uber", "rappi", "pedidosya", "cabify", "didi"],
  lagos: ["bolt", "uber", "gokada", "chowdeck", "glovo"],
  nairobi: ["bolt", "uber", "glovo", "little", "faras"],
  accra: ["bolt", "uber", "glovo", "yango", "jumiafood"],
  cairo: ["uber", "careem", "talabat", "breadfast", "elmenus"],
  johannesburg: ["bolt", "uber", "mrd", "sixty60", "takealot"],
  addisababa: ["ride", "feres", "zayride", "deliveraddis", "beu"],
  daressalaam: ["bolt", "uber", "littlecab", "piki", "jumiafood"],
  kampala: ["safeboda", "bolt", "uber", "jumiafood", "glovo"],
  casablanca: ["careem", "indrive", "glovo", "yassir", "kaalix"],
  istanbul: ["bitaksi", "getir", "yemeksepeti", "trendyolgo", "marti"],
  dubai: ["careem", "uber", "talabat", "deliveroo", "noon"],
  riyadh: ["careem", "uber", "hungerstation", "jahez", "mrsool"],
  baghdad: ["careem", "baly", "talabat", "lezzoo", "alsaree3"],
  amman: ["careem", "uber", "talabat", "tawseela", "jeeny"],
  moscow: ["yandexgo", "delivery", "samokat", "sbermarket", "ozon"],
  kyiv: ["bolt", "uklon", "glovo", "rocket", "zakaz"],
  warsaw: ["bolt", "uber", "glovo", "wolt", "pyszne"],
  bucharest: ["bolt", "uber", "glovo", "tazz", "freenow"],
  madrid: ["glovo", "ubereats", "cabify", "bolt", "justeat"],
  almaty: ["yandexgo", "indrive", "wolt", "glovo", "chocofood"],
  tashkent: ["yandexgo", "mytaxi", "express24", "uzum", "wolt"],
  baku: ["bolt", "uber", "wolt", "yango", "aznaxis"],
  singapore: ["grab", "gojek", "foodpanda", "deliveroo", "ryde"],
  tokyo: ["ubereats", "demaecan", "wolt", "menu", "gotaxi"],
  seoul: ["baemin", "coupangeats", "kakaot", "yogiyo", "tada"],
  tbilisi: ["bolt", "yandexgo", "wolt", "glovo", "maxim"],
  belgrade: ["wolt", "glovo", "cargo", "yandexgo", "donesi"],
  lisbon: ["uber", "bolt", "glovo", "ubereats", "freenow"],
  milan: ["glovo", "deliveroo", "justeat", "ubereats", "freenow"],
  dakar: ["yango", "heetch", "yassir", "jumiafood", "kai"],
  quito: ["uber", "cabify", "rappi", "pedidosya", "indrive"],
};

const pick = (arr, i) => arr[i % arr.length];

/**
 * Build `count` personas spread across the given cities.
 *
 * `engagement` multiplies how often someone posts, chats and likes. 1 is the
 * default population; 5 is a crowd that barely stops typing. It is deliberately
 * NOT applied to breakiness — making people take five times as many breaks
 * would quieten the run, which is the opposite of what the dial is for.
 *
 * Weights are probabilities per tick, so they are clamped below 1. The clamp
 * sits at 0.95 rather than 1 so that even at extreme multipliers the population
 * keeps a little variance instead of collapsing into every agent doing every
 * action on every tick — identical bots find identical bugs.
 */
export function buildPersonas(count, cityKeys = Object.keys(CITIES), engagement = 1) {
  const keys = cityKeys.filter((c) => CITIES[c]);
  if (!keys.length) throw new Error(`Unknown cities. Available: ${Object.keys(CITIES).join(", ")}`);
  const e = Number.isFinite(engagement) && engagement > 0 ? engagement : 1;
  const scale = (w) => Math.min(0.95, w * e);

  const personas = [];
  for (let i = 0; i < count; i++) {
    const cityKey = keys[i % keys.length];
    const city = CITIES[cityKey];
    const n = Math.floor(i / keys.length);
    personas.push({
      id: `sim${String(i + 1).padStart(3, "0")}`,
      cityKey,
      city,
      name: pick(NAMES[cityKey], n),
      platform: pick(PLATFORMS[cityKey], n),
      rate: city.rate,
      // Behaviour weights — the reason the population feels human.
      postiness: scale(0.05 + (i % 5) * 0.05), // 0.05 – 0.25 chance per tick
      chattiness: scale(0.05 + (i % 4) * 0.06),
      likeliness: scale(0.15 + (i % 3) * 0.2),
      breakiness: 0.03 + (i % 6) * 0.02, // not scaled - see the note above

      speedKmh: 18 + (i % 5) * 6, // 18–42 km/h city driving
    });
  }
  return personas;
}

export const chatterFor = (cityKey, n) => pick(CHATTER[cityKey] ?? CHATTER.manila, n);
export const replyLine = (n) => pick(REPLIES, n);
